apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: airesume
  labels:
    app: airesume-backend
    app.kubernetes.io/name: airesumebuilder
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: airesume-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
