apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: airesume
  labels:
    app: airesume-frontend
    app.kubernetes.io/name: airesumebuilder
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: airesume-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
