apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: airesume
  labels:
    app: airesume-mongodb
    app.kubernetes.io/name: airesumebuilder
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: airesume-mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
