apiVersion: v1
kind: Secret
metadata:
  name: airesume-secrets
  namespace: airesume
  labels:
    app.kubernetes.io/name: airesumebuilder
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvYWlyZXN1bWVidWlsZGVy
  JWT_SECRET: Y2hhbmdlLW1lLXRvLWEtcmVhbC1zZWNyZXQ=
  GEMINI_API_KEY: eW91ci1nZW1pbmktYXBpLWtleS1oZXJl
